"""Deterministic hash embedding fallback with no external dependencies."""

from __future__ import annotations

import hashlib
from typing import List


def hash_embedding(text: str, dim: int = 384) -> List[float]:
    """Return a deterministic ``dim``-dimensional embedding for ``text``.

    The vector is generated by iterative SHA-256 hashing of the UTF-8 text.
    Each byte is mapped to the interval ``[-1, 1]``. The result is stable
    across runs and platforms so the exocortex can function without any
    external embedding model.
    """
    if not isinstance(dim, int) or dim <= 0 or dim % 4 != 0:
        raise ValueError("dim must be a positive multiple of 4")

    text_bytes = text.encode("utf-8")
    needed = dim
    chunks: List[bytes] = []
    seed = hashlib.sha256(text_bytes).digest()
    while len(b"".join(chunks)) < needed:
        seed = hashlib.sha256(seed + text_bytes).digest()
        chunks.append(seed)

    data = b"".join(chunks)[:needed]
    # Map each byte to [-1, 1]
    return [(byte / 255.0) * 2.0 - 1.0 for byte in data]
